/* $Rev: 25011 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>ExtractDataModel</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtractData_v103
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
    [System.Xml.Serialization.XmlRootAttribute("GetExtractByIdResponse", Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract", IsNullable=false)]
    public partial class GetExtractByIdResponseType {
        
        private object itemField;
        
        [System.Xml.Serialization.XmlElementAttribute("embeddable", typeof(GetExtractByIdResponseTypeEmbeddable))]
        [System.Xml.Serialization.XmlElementAttribute("Extract", typeof(Extract), Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
    public partial class GetExtractByIdResponseTypeEmbeddable {
        
        private System.DateTime cadasterStateField;
        
        private string cadasterOrganisationNameField;
        
        private string dataownerNameCadastralSurveyingField;
        
        private System.DateTime transferFromSourceCadastralSurveyingField;
        
        private GetExtractByIdResponseTypeEmbeddableDatasource[] datasourceField;
        
        private byte[] pdfField;
        
        public System.DateTime cadasterState {
            get {
                return this.cadasterStateField;
            }
            set {
                this.cadasterStateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string cadasterOrganisationName {
            get {
                return this.cadasterOrganisationNameField;
            }
            set {
                this.cadasterOrganisationNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string dataownerNameCadastralSurveying {
            get {
                return this.dataownerNameCadastralSurveyingField;
            }
            set {
                this.dataownerNameCadastralSurveyingField = value;
            }
        }
        
        public System.DateTime transferFromSourceCadastralSurveying {
            get {
                return this.transferFromSourceCadastralSurveyingField;
            }
            set {
                this.transferFromSourceCadastralSurveyingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("datasource")]
        public GetExtractByIdResponseTypeEmbeddableDatasource[] datasource {
            get {
                return this.datasourceField;
            }
            set {
                this.datasourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
    public partial class GetExtractByIdResponseTypeEmbeddableDatasource {
        
        private Theme topicField;
        
        private string dataownerNameField;
        
        private System.DateTime transferFromSourceField;
        
        public Theme topic {
            get {
                return this.topicField;
            }
            set {
                this.topicField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string dataownerName {
            get {
                return this.dataownerNameField;
            }
            set {
                this.dataownerNameField = value;
            }
        }
        
        public System.DateTime transferFromSource {
            get {
                return this.transferFromSourceField;
            }
            set {
                this.transferFromSourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Theme {
        
        private string codeField;
        
        private LocalisedText textField;
        
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        public LocalisedText Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class LocalisedText {
        
        private LanguageCode languageField;
        
        private bool languageFieldSpecified;
        
        private string textField;
        
        public LanguageCode Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public enum LanguageCode {
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        fr,
        
        /// <remarks/>
        it,
        
        /// <remarks/>
        rm,
        
        /// <remarks/>
        en,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class ExclusionOfLiability {
        
        private LocalisedText[] titleField;
        
        private LocalisedMText[] contentField;
        
        private extensions extensionsField;
        
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalisedText[] Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedMText[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class LocalisedMText {
        
        private LanguageCode languageField;
        
        private bool languageFieldSpecified;
        
        private string textField;
        
        public LanguageCode Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class extensions {
        
        private System.Xml.XmlElement[] anyField;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class LocalisedUri {
        
        private LanguageCode languageField;
        
        private bool languageFieldSpecified;
        
        private string textField;
        
        public LanguageCode Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Article))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class DocumentBase {
        
        private DocumentBaseDocumentType documentTypeField;
        
        private LocalisedUri[] textAtWebField;
        
        private Lawstatus lawstatusField;
        
        private extensions extensionsField;
        
        public DocumentBaseDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedUri[] TextAtWeb {
            get {
                return this.textAtWebField;
            }
            set {
                this.textAtWebField = value;
            }
        }
        
        public Lawstatus Lawstatus {
            get {
                return this.lawstatusField;
            }
            set {
                this.lawstatusField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public enum DocumentBaseDocumentType {
        
        /// <remarks/>
        LegalProvision,
        
        /// <remarks/>
        Law,
        
        /// <remarks/>
        Hint,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Lawstatus {
        
        private LawstatusCode codeField;
        
        private LocalisedText textField;
        
        public LawstatusCode Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        public LocalisedText Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public enum LawstatusCode {
        
        /// <remarks/>
        inForce,
        
        /// <remarks/>
        runningModifications,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Document : DocumentBase {
        
        private LocalisedText[] titleField;
        
        private LocalisedText[] officialTitleField;
        
        private LocalisedText[] abbreviationField;
        
        private string officialNumberField;
        
        private CantonCode cantonField;
        
        private bool cantonFieldSpecified;
        
        private string municipalityField;
        
        private Office responsibleOfficeField;
        
        private string[] articleNumberField;
        
        private Article[] articleField;
        
        private Document[] referenceField;
        
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalisedText[] Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalisedText[] OfficialTitle {
            get {
                return this.officialTitleField;
            }
            set {
                this.officialTitleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalisedText[] Abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string OfficialNumber {
            get {
                return this.officialNumberField;
            }
            set {
                this.officialNumberField = value;
            }
        }
        
        public CantonCode Canton {
            get {
                return this.cantonField;
            }
            set {
                this.cantonField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CantonSpecified {
            get {
                return this.cantonFieldSpecified;
            }
            set {
                this.cantonFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
        
        public Office ResponsibleOffice {
            get {
                return this.responsibleOfficeField;
            }
            set {
                this.responsibleOfficeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ArticleNumber", DataType="normalizedString")]
        public string[] ArticleNumber {
            get {
                return this.articleNumberField;
            }
            set {
                this.articleNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Article")]
        public Article[] Article {
            get {
                return this.articleField;
            }
            set {
                this.articleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public Document[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public enum CantonCode {
        
        /// <remarks/>
        ZH,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        UR,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        OW,
        
        /// <remarks/>
        NW,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        ZG,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TI,
        
        /// <remarks/>
        VD,
        
        /// <remarks/>
        VS,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        JU,
        
        /// <remarks/>
        FL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Office {
        
        private LocalisedText[] nameField;
        
        private WebReference officeAtWebField;
        
        private string uIDField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string streetField;
        
        private string numberField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private extensions extensionsField;
        
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalisedText[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public WebReference OfficeAtWeb {
            get {
                return this.officeAtWebField;
            }
            set {
                this.officeAtWebField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class WebReference {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Article : DocumentBase {
        
        private string numberField;
        
        private LocalisedMText[] textField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedMText[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class LegendEntry {
        
        private object itemField;
        
        private LocalisedText[] legendTextField;
        
        private string typeCodeField;
        
        private string typeCodelistField;
        
        private Theme themeField;
        
        private string subThemeField;
        
        private extensions extensionsField;
        
        [System.Xml.Serialization.XmlElementAttribute("Symbol", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("SymbolRef", typeof(string), DataType="anyURI")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalisedText[] LegendText {
            get {
                return this.legendTextField;
            }
            set {
                this.legendTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string TypeCodelist {
            get {
                return this.typeCodelistField;
            }
            set {
                this.typeCodelistField = value;
            }
        }
        
        public Theme Theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string SubTheme {
            get {
                return this.subThemeField;
            }
            set {
                this.subThemeField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Map {
        
        private byte[] imageField;
        
        private string referenceWMSField;
        
        private WebReference legendAtWebField;
        
        private LegendEntry[] otherLegendField;

        private DataExtract.Gml.Simplified.PointPropertyType[] itemsField;
        
        private ItemsChoiceType3[] itemsElementNameField;
        
        private string layerIndexField;
        
        private double layerOpacityField;
        
        private extensions extensionsField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string ReferenceWMS {
            get {
                return this.referenceWMSField;
            }
            set {
                this.referenceWMSField = value;
            }
        }
        
        public WebReference LegendAtWeb {
            get {
                return this.legendAtWebField;
            }
            set {
                this.legendAtWebField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OtherLegend")]
        public LegendEntry[] OtherLegend {
            get {
                return this.otherLegendField;
            }
            set {
                this.otherLegendField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("max_NS03", typeof(DataExtract.Gml.Simplified.PointPropertyType))]
        [System.Xml.Serialization.XmlElementAttribute("max_NS95", typeof(DataExtract.Gml.Simplified.PointPropertyType))]
        [System.Xml.Serialization.XmlElementAttribute("min_NS03", typeof(DataExtract.Gml.Simplified.PointPropertyType))]
        [System.Xml.Serialization.XmlElementAttribute("min_NS95", typeof(DataExtract.Gml.Simplified.PointPropertyType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public DataExtract.Gml.Simplified.PointPropertyType[] Items
        {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType3[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string layerIndex {
            get {
                return this.layerIndexField;
            }
            set {
                this.layerIndexField = value;
            }
        }
        
        public double layerOpacity {
            get {
                return this.layerOpacityField;
            }
            set {
                this.layerOpacityField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData", IncludeInSchema=false)]
    public enum ItemsChoiceType3 {
        
        /// <remarks/>
        max_NS03,
        
        /// <remarks/>
        max_NS95,
        
        /// <remarks/>
        min_NS03,
        
        /// <remarks/>
        min_NS95,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Geometry {

        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private Lawstatus lawstatusField;
        
        private string metadataOfGeographicalBaseDataField;
        
        private Office responsibleOfficeField;
        
        private extensions extensionsField;

        [System.Xml.Serialization.XmlElementAttribute("Line", typeof(DataExtract.Gml.Simplified.CurvePropertyType))]
        [System.Xml.Serialization.XmlElementAttribute("Point", typeof(DataExtract.Gml.Simplified.PointPropertyType))]
        [System.Xml.Serialization.XmlElementAttribute("Surface", typeof(DataExtract.Gml.Simplified.SurfacePropertyType))]
        //[System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        public Lawstatus Lawstatus {
            get {
                return this.lawstatusField;
            }
            set {
                this.lawstatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string MetadataOfGeographicalBaseData {
            get {
                return this.metadataOfGeographicalBaseDataField;
            }
            set {
                this.metadataOfGeographicalBaseDataField = value;
            }
        }
        
        public Office ResponsibleOffice {
            get {
                return this.responsibleOfficeField;
            }
            set {
                this.responsibleOfficeField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Line,
        
        /// <remarks/>
        Point,
        
        /// <remarks/>
        Surface,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class RestrictionOnLandownership {
        
        private LocalisedMText[] informationField;
        
        private Theme themeField;
        
        private string subThemeField;
        
        private string typeCodeField;
        
        private string typeCodelistField;
        
        private Lawstatus lawstatusField;
        
        private string areaShareField;
        
        private string lengthShareField;
        
        private string nrOfPointsField;
        
        private decimal partInPercentField;
        
        private bool partInPercentFieldSpecified;
        
        private object itemField;
        
        private Geometry[] geometryField;
        
        private Map mapField;
        
        private DocumentBase[] legalProvisionsField;
        
        private Office responsibleOfficeField;
        
        private extensions extensionsField;
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedMText[] Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
        
        public Theme Theme {
            get {
                return this.themeField;
            }
            set {
                this.themeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string SubTheme {
            get {
                return this.subThemeField;
            }
            set {
                this.subThemeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string TypeCodelist {
            get {
                return this.typeCodelistField;
            }
            set {
                this.typeCodelistField = value;
            }
        }
        
        public Lawstatus Lawstatus {
            get {
                return this.lawstatusField;
            }
            set {
                this.lawstatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string AreaShare {
            get {
                return this.areaShareField;
            }
            set {
                this.areaShareField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string LengthShare {
            get {
                return this.lengthShareField;
            }
            set {
                this.lengthShareField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NrOfPoints {
            get {
                return this.nrOfPointsField;
            }
            set {
                this.nrOfPointsField = value;
            }
        }
        
        public decimal PartInPercent {
            get {
                return this.partInPercentField;
            }
            set {
                this.partInPercentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartInPercentSpecified {
            get {
                return this.partInPercentFieldSpecified;
            }
            set {
                this.partInPercentFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Symbol", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("SymbolRef", typeof(string), DataType="anyURI")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Geometry")]
        public Geometry[] Geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
            }
        }
        
        public Map Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("LegalProvisions")]
        public DocumentBase[] LegalProvisions {
            get {
                return this.legalProvisionsField;
            }
            set {
                this.legalProvisionsField = value;
            }
        }
        
        public Office ResponsibleOffice {
            get {
                return this.responsibleOfficeField;
            }
            set {
                this.responsibleOfficeField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class RealEstate_DPR {
        
        private string numberField;
        
        private string identDNField;
        
        private string eGRIDField;
        
        private RealEstateType typeField;
        
        private CantonCode cantonField;
        
        private string municipalityField;
        
        private string subunitOfLandRegisterField;
        
        private string fosNrField;
        
        private string metadataOfGeographicalBaseDataField;
        
        private string landRegistryAreaField;

        private DataExtract.Gml.Simplified.MultiSurfacePropertyType limitField;
        
        private RestrictionOnLandownership[] restrictionOnLandownershipField;
        
        private Map planForLandRegisterField;
        
        private Map planForLandRegisterMainPageField;
        
        private Document[] referenceField;
        
        private extensions extensionsField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string IdentDN {
            get {
                return this.identDNField;
            }
            set {
                this.identDNField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string EGRID {
            get {
                return this.eGRIDField;
            }
            set {
                this.eGRIDField = value;
            }
        }
        
        public RealEstateType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        public CantonCode Canton {
            get {
                return this.cantonField;
            }
            set {
                this.cantonField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string Municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string SubunitOfLandRegister {
            get {
                return this.subunitOfLandRegisterField;
            }
            set {
                this.subunitOfLandRegisterField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FosNr {
            get {
                return this.fosNrField;
            }
            set {
                this.fosNrField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string MetadataOfGeographicalBaseData {
            get {
                return this.metadataOfGeographicalBaseDataField;
            }
            set {
                this.metadataOfGeographicalBaseDataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string LandRegistryArea {
            get {
                return this.landRegistryAreaField;
            }
            set {
                this.landRegistryAreaField = value;
            }
        }

        public DataExtract.Gml.Simplified.MultiSurfacePropertyType Limit
        {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RestrictionOnLandownership")]
        public RestrictionOnLandownership[] RestrictionOnLandownership {
            get {
                return this.restrictionOnLandownershipField;
            }
            set {
                this.restrictionOnLandownershipField = value;
            }
        }
        
        public Map PlanForLandRegister {
            get {
                return this.planForLandRegisterField;
            }
            set {
                this.planForLandRegisterField = value;
            }
        }
        
        public Map PlanForLandRegisterMainPage {
            get {
                return this.planForLandRegisterMainPageField;
            }
            set {
                this.planForLandRegisterMainPageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public Document[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public enum RealEstateType {
        
        /// <remarks/>
        RealEstate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.BuildingRight")]
        Distinct_and_permanent_rightsBuildingRight,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.right_to_spring_water")]
        Distinct_and_permanent_rightsright_to_spring_water,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.concession")]
        Distinct_and_permanent_rightsconcession,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Distinct_and_permanent_rights.other")]
        Distinct_and_permanent_rightsother,
        
        /// <remarks/>
        Mineral_rights,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Glossary {
        
        private LocalisedText[] titleField;
        
        private LocalisedMText[] contentField;
        
        private extensions extensionsField;
        
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalisedText[] Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedMText[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ObjectType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string idField;
        
        private string mimeTypeField;
        
        private string encodingField;
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SPKIDataType {
        
        private byte[][] sPKISexpField;
        
        private System.Xml.XmlElement anyField;
        
        [System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType="base64Binary")]
        public byte[][] SPKISexp {
            get {
                return this.sPKISexpField;
            }
            set {
                this.sPKISexpField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class PGPDataType {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        PGPKeyID,
        
        /// <remarks/>
        PGPKeyPacket,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType {
        
        private string x509IssuerNameField;
        
        private string x509SerialNumberField;
        
        public string X509IssuerName {
            get {
                return this.x509IssuerNameField;
            }
            set {
                this.x509IssuerNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string X509SerialNumber {
            get {
                return this.x509SerialNumberField;
            }
            set {
                this.x509SerialNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType))]
        [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        X509CRL,
        
        /// <remarks/>
        X509Certificate,
        
        /// <remarks/>
        X509IssuerSerial,
        
        /// <remarks/>
        X509SKI,
        
        /// <remarks/>
        X509SubjectName,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RetrievalMethodType {
        
        private TransformType[] transformsField;
        
        private string uRIField;
        
        private string typeField;
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string algorithmField;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RSAKeyValueType {
        
        private byte[] modulusField;
        
        private byte[] exponentField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Modulus {
            get {
                return this.modulusField;
            }
            set {
                this.modulusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Exponent {
            get {
                return this.exponentField;
            }
            set {
                this.exponentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DSAKeyValueType {
        
        private byte[] pField;
        
        private byte[] qField;
        
        private byte[] gField;
        
        private byte[] yField;
        
        private byte[] jField;
        
        private byte[] seedField;
        
        private byte[] pgenCounterField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PgenCounter {
            get {
                return this.pgenCounterField;
            }
            set {
                this.pgenCounterField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyValueType {
        
        private object itemField;
        
        private string[] textField;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType {
        
        private object[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        private string[] textField;
        
        private string idField;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType))]
        [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType))]
        [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType))]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        KeyName,
        
        /// <remarks/>
        KeyValue,
        
        /// <remarks/>
        MgmtData,
        
        /// <remarks/>
        PGPData,
        
        /// <remarks/>
        RetrievalMethod,
        
        /// <remarks/>
        SPKIData,
        
        /// <remarks/>
        X509Data,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureValueType {
        
        private string idField;
        
        private byte[] valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType {
        
        private TransformType[] transformsField;
        
        private DigestMethodType digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethodType {
        
        private string hMACOutputLengthField;
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string HMACOutputLength {
            get {
                return this.hMACOutputLengthField;
            }
            set {
                this.hMACOutputLengthField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType {
        
        private CanonicalizationMethodType canonicalizationMethodField;
        
        private SignatureMethodType signatureMethodField;
        
        private ReferenceType[] referenceField;
        
        private string idField;
        
        public CanonicalizationMethodType CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        public SignatureMethodType SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ReferenceType[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureType {
        
        private SignedInfoType signedInfoField;
        
        private SignatureValueType signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private ObjectType[] objectField;
        
        private string idField;
        
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        public SignatureValueType SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Object")]
        public ObjectType[] Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData")]
    public partial class Extract {
        
        private System.DateTime creationDateField;
        
        private SignatureType signatureField;
        
        private Theme[] concernedThemeField;
        
        private Theme[] notConcernedThemeField;
        
        private Theme[] themeWithoutDataField;
        
        private bool isReducedField;
        
        private object itemField;
        
        private object item1Field;
        
        private object item2Field;
        
        private object item3Field;
        
        private string extractIdentifierField;
        
        private object item4Field;
        
        private LocalisedMText[] generalInformationField;
        
        private LocalisedMText[] baseDataField;
        
        private Glossary[] glossaryField;
        
        private RealEstate_DPR realEstateField;
        
        private ExclusionOfLiability[] exclusionOfLiabilityField;
        
        private Office pLRCadastreAuthorityField;
        
        private LocalisedMText[] certificationField;
        
        private LocalisedUri[] certificationAtWebField;
        
        private extensions extensionsField;
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ConcernedTheme")]
        public Theme[] ConcernedTheme {
            get {
                return this.concernedThemeField;
            }
            set {
                this.concernedThemeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("NotConcernedTheme")]
        public Theme[] NotConcernedTheme {
            get {
                return this.notConcernedThemeField;
            }
            set {
                this.notConcernedThemeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ThemeWithoutData")]
        public Theme[] ThemeWithoutData {
            get {
                return this.themeWithoutDataField;
            }
            set {
                this.themeWithoutDataField = value;
            }
        }
        
        public bool isReduced {
            get {
                return this.isReducedField;
            }
            set {
                this.isReducedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("LogoPLRCadastre", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("LogoPLRCadastreRef", typeof(string), DataType="anyURI")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FederalLogo", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("FederalLogoRef", typeof(string), DataType="anyURI")]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CantonalLogo", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("CantonalLogoRef", typeof(string), DataType="anyURI")]
        public object Item2 {
            get {
                return this.item2Field;
            }
            set {
                this.item2Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MunicipalityLogo", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("MunicipalityLogoRef", typeof(string), DataType="anyURI")]
        public object Item3 {
            get {
                return this.item3Field;
            }
            set {
                this.item3Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string ExtractIdentifier {
            get {
                return this.extractIdentifierField;
            }
            set {
                this.extractIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("QRCode", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("QRCodeRef", typeof(string), DataType="anyURI")]
        public object Item4 {
            get {
                return this.item4Field;
            }
            set {
                this.item4Field = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedMText[] GeneralInformation {
            get {
                return this.generalInformationField;
            }
            set {
                this.generalInformationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedMText[] BaseData {
            get {
                return this.baseDataField;
            }
            set {
                this.baseDataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Glossary")]
        public Glossary[] Glossary {
            get {
                return this.glossaryField;
            }
            set {
                this.glossaryField = value;
            }
        }
        
        public RealEstate_DPR RealEstate {
            get {
                return this.realEstateField;
            }
            set {
                this.realEstateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ExclusionOfLiability")]
        public ExclusionOfLiability[] ExclusionOfLiability {
            get {
                return this.exclusionOfLiabilityField;
            }
            set {
                this.exclusionOfLiabilityField = value;
            }
        }
        
        public Office PLRCadastreAuthority {
            get {
                return this.pLRCadastreAuthorityField;
            }
            set {
                this.pLRCadastreAuthorityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedMText[] Certification {
            get {
                return this.certificationField;
            }
            set {
                this.certificationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalisedText", IsNullable=false)]
        public LocalisedUri[] CertificationAtWeb {
            get {
                return this.certificationAtWebField;
            }
            set {
                this.certificationAtWebField = value;
            }
        }
        
        public extensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
    [System.Xml.Serialization.XmlRootAttribute("GetEGRIDResponse", Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract", IsNullable=false)]
    public partial class GetEGRIDResponseType {
        
        private string egridField;
        
        private string numberField;
        
        private string identDNField;
        
        [System.Xml.Serialization.XmlElementAttribute("egrid", DataType="token")]
        public string egrid {
            get {
                return this.egridField;
            }
            set {
                this.egridField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("number", DataType="token")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("identDN", DataType="token")]
        public string identDN {
            get {
                return this.identDNField;
            }
            set {
                this.identDNField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract")]
    [System.Xml.Serialization.XmlRootAttribute("GetCapabilitiesResponse", Namespace="http://schemas.geo.admin.ch/V_D/OeREB/1.0/Extract", IsNullable=false)]
    public partial class GetCapabilitiesResponseType {
        
        private Theme[] topicField;
        
        private string[] municipalityField;
        
        private string[] flavourField;
        
        private string[] languageField;
        
        private string[] crsField;
        
        [System.Xml.Serialization.XmlElementAttribute("topic")]
        public Theme[] topic {
            get {
                return this.topicField;
            }
            set {
                this.topicField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("municipality", DataType="integer")]
        public string[] municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("flavour", DataType="token")]
        public string[] flavour {
            get {
                return this.flavourField;
            }
            set {
                this.flavourField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("language", DataType="token")]
        public string[] language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("crs", DataType="token")]
        public string[] crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
            }
        }
    }
}
