/* $Rev: 29788 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net45","NameSpace":"ExtractDataModel_v20","CollectionObjectType":"Array","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ExtractDataModel_v20
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/Extract")]
    [XmlRootAttribute("GetExtractByIdResponse", Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/Extract", IsNullable = false)]
    public partial class GetExtractByIdResponseType
    {
        #region Private fields
        private Extract _extract;
        #endregion

        public GetExtractByIdResponseType()
        {
            _extract = new Extract();
        }

        [XmlElement(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
        public Extract Extract
        {
            get
            {
                return _extract;
            }
            set
            {
                _extract = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Extract
    {
        #region Private fields
        private System.DateTime _creationDate;
        //private SignatureType _signature;
        private Theme[] _concernedTheme;
        private Theme[] _notConcernedTheme;
        private Theme[] _themeWithoutData;
        private object _item;
        private object _item1;
        private object _item2;
        private object _item3;
        private string _extractIdentifier;
        private object _item4;
        private LocalisedMText[] _generalInformation;
        private Glossary[] _glossary;
        private RealEstate_DPR _realEstate;
        private Disclaimer[] _disclaimer;
        private Office _pLRCadastreAuthority;
        private System.DateTime _updateDateCS;
        private extensions _extensions;
        private string _id;
        private System.Xml.XmlAttribute[] _anyAttr;
        #endregion

        public Extract()
        {
            _extensions = new extensions();
            _pLRCadastreAuthority = new Office();
            _realEstate = new RealEstate_DPR();
        }

        public System.DateTime CreationDate
        {
            get
            {
                return _creationDate;
            }
            set
            {
                _creationDate = value;
            }
        }

        //public SignatureType Signature
        //{
        //    get
        //    {
        //        return _signature;
        //    }
        //    set
        //    {
        //        _signature = value;
        //    }
        //}

        [XmlElement("ConcernedTheme")]
        public Theme[] ConcernedTheme
        {
            get
            {
                return _concernedTheme;
            }
            set
            {
                _concernedTheme = value;
            }
        }

        [XmlElement("NotConcernedTheme")]
        public Theme[] NotConcernedTheme
        {
            get
            {
                return _notConcernedTheme;
            }
            set
            {
                _notConcernedTheme = value;
            }
        }

        [XmlElement("ThemeWithoutData")]
        public Theme[] ThemeWithoutData
        {
            get
            {
                return _themeWithoutData;
            }
            set
            {
                _themeWithoutData = value;
            }
        }

        [XmlElement("LogoPLRCadastre", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("LogoPLRCadastreRef", typeof(string), DataType = "anyURI")]
        public object Item
        {
            get
            {
                return _item;
            }
            set
            {
                _item = value;
            }
        }

        [XmlElement("FederalLogo", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("FederalLogoRef", typeof(string), DataType = "anyURI")]
        public object Item1
        {
            get
            {
                return _item1;
            }
            set
            {
                _item1 = value;
            }
        }

        [XmlElement("CantonalLogo", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("CantonalLogoRef", typeof(string), DataType = "anyURI")]
        public object Item2
        {
            get
            {
                return _item2;
            }
            set
            {
                _item2 = value;
            }
        }

        [XmlElement("MunicipalityLogo", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("MunicipalityLogoRef", typeof(string), DataType = "anyURI")]
        public object Item3
        {
            get
            {
                return _item3;
            }
            set
            {
                _item3 = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string ExtractIdentifier
        {
            get
            {
                return _extractIdentifier;
            }
            set
            {
                _extractIdentifier = value;
            }
        }

        [XmlElement("QRCode", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("QRCodeRef", typeof(string), DataType = "anyURI")]
        public object Item4
        {
            get
            {
                return _item4;
            }
            set
            {
                _item4 = value;
            }
        }

        [XmlArrayItemAttribute("LocalisedText", typeof(LocalisedMText), IsNullable = false)]
        public LocalisedMText[] GeneralInformation
        {
            get
            {
                return _generalInformation;
            }
            set
            {
                _generalInformation = value;
            }
        }

        [XmlElement("Glossary")]
        public Glossary[] Glossary
        {
            get
            {
                return _glossary;
            }
            set
            {
                _glossary = value;
            }
        }

        public RealEstate_DPR RealEstate
        {
            get
            {
                return _realEstate;
            }
            set
            {
                _realEstate = value;
            }
        }

        [XmlElement("Disclaimer")]
        public Disclaimer[] Disclaimer
        {
            get
            {
                return _disclaimer;
            }
            set
            {
                _disclaimer = value;
            }
        }

        public Office PLRCadastreAuthority
        {
            get
            {
                return _pLRCadastreAuthority;
            }
            set
            {
                _pLRCadastreAuthority = value;
            }
        }

        public System.DateTime UpdateDateCS
        {
            get
            {
                return _updateDateCS;
            }
            set
            {
                _updateDateCS = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return _anyAttr;
            }
            set
            {
                _anyAttr = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Theme
    {
        #region Private fields
        private string _code;
        private string _subCode;
        private LocalisedText[] _text;
        #endregion

        public string Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        public string SubCode
        {
            get
            {
                return _subCode;
            }
            set
            {
                _subCode = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedText
    {
        #region Private fields
        private LanguageCode _language;
        private string _text;
        #endregion

        public LanguageCode Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum LanguageCode
    {
        de,
        fr,
        it,
        rm,
        en,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Disclaimer
    {
        #region Private fields
        private LocalisedText[] _title;
        private LocalisedMText[] _content;
        private extensions _extensions;
        #endregion

        public Disclaimer()
        {
            _extensions = new extensions();
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }

        [XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedMText[] Content
        {
            get
            {
                return _content;
            }
            set
            {
                _content = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedMText
    {
        #region Private fields
        private LanguageCode _language;
        private string _text;
        #endregion

        public LanguageCode Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class extensions
    {
        #region Private fields
        private System.Xml.XmlElement[] _any;
        #endregion

        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Office
    {
        #region Private fields
        private LocalisedText[] _name;
        private LocalisedUri[] _officeAtWeb;
        private string _uID;
        private string _line1;
        private string _line2;
        private string _street;
        private string _number;
        private string _postalCode;
        private string _city;
        private extensions _extensions;
        #endregion

        public Office()
        {
            _extensions = new extensions();
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        [XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedUri[] OfficeAtWeb
        {
            get
            {
                return _officeAtWeb;
            }
            set
            {
                _officeAtWeb = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string UID
        {
            get
            {
                return _uID;
            }
            set
            {
                _uID = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string Line1
        {
            get
            {
                return _line1;
            }
            set
            {
                _line1 = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string Line2
        {
            get
            {
                return _line2;
            }
            set
            {
                _line2 = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string Street
        {
            get
            {
                return _street;
            }
            set
            {
                _street = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string Number
        {
            get
            {
                return _number;
            }
            set
            {
                _number = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string PostalCode
        {
            get
            {
                return _postalCode;
            }
            set
            {
                _postalCode = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string City
        {
            get
            {
                return _city;
            }
            set
            {
                _city = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedUri
    {
        #region Private fields
        private LanguageCode _language;
        private string _text;
        #endregion

        public LanguageCode Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        [XmlElement(DataType = "anyURI")]
        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class DocumentType
    {
        #region Private fields
        private DocumentTypeCode _code;
        private LocalisedText[] _text;
        #endregion

        public DocumentTypeCode Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum DocumentTypeCode
    {
        LegalProvision,
        Law,
        Hint,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Document
    {
        #region Private fields
        private DocumentType _type;
        private LocalisedText[] _title;
        private LocalisedText[] _abbreviation;
        private LocalisedText[] _officialNumber;
        private LocalisedUri[] _textAtWeb;
        private string[] _articleNumber;
        private Lawstatus _lawstatus;
        private string _index;
        private Office _responsibleOffice;
        private extensions _extensions;
        #endregion

        public Document()
        {
            _extensions = new extensions();
            _responsibleOffice = new Office();
            _lawstatus = new Lawstatus();
            _type = new DocumentType();
        }

        public DocumentType Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Abbreviation
        {
            get
            {
                return _abbreviation;
            }
            set
            {
                _abbreviation = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] OfficialNumber
        {
            get
            {
                return _officialNumber;
            }
            set
            {
                _officialNumber = value;
            }
        }

        [XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedUri[] TextAtWeb
        {
            get
            {
                return _textAtWeb;
            }
            set
            {
                _textAtWeb = value;
            }
        }

        [XmlElement("ArticleNumber", DataType = "normalizedString")]
        public string[] ArticleNumber
        {
            get
            {
                return _articleNumber;
            }
            set
            {
                _articleNumber = value;
            }
        }

        public Lawstatus Lawstatus
        {
            get
            {
                return _lawstatus;
            }
            set
            {
                _lawstatus = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string Index
        {
            get
            {
                return _index;
            }
            set
            {
                _index = value;
            }
        }

        public Office ResponsibleOffice
        {
            get
            {
                return _responsibleOffice;
            }
            set
            {
                _responsibleOffice = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Lawstatus
    {
        #region Private fields
        private LawstatusCode _code;
        private LocalisedText[] _text;
        #endregion

        public LawstatusCode Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum LawstatusCode
    {
        inForce,
        changeWithPreEffect,
        changeWithoutPreEffect,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LegendEntry
    {
        #region Private fields
        private object _item;
        private LocalisedText[] _legendText;
        private string _typeCode;
        private string _typeCodelist;
        private Theme _theme;
        private extensions _extensions;
        #endregion

        public LegendEntry()
        {
            _extensions = new extensions();
            _theme = new Theme();
        }

        [XmlElement("Symbol", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("SymbolRef", typeof(string), DataType = "anyURI")]
        public object Item
        {
            get
            {
                return _item;
            }
            set
            {
                _item = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] LegendText
        {
            get
            {
                return _legendText;
            }
            set
            {
                _legendText = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string TypeCode
        {
            get
            {
                return _typeCode;
            }
            set
            {
                _typeCode = value;
            }
        }

        [XmlElement(DataType = "anyURI")]
        public string TypeCodelist
        {
            get
            {
                return _typeCodelist;
            }
            set
            {
                _typeCodelist = value;
            }
        }

        public Theme Theme
        {
            get
            {
                return _theme;
            }
            set
            {
                _theme = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class LocalisedBlob
    {
        #region Private fields
        private LanguageCode _language;
        private byte[] _blob;
        #endregion

        public LanguageCode Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] Blob
        {
            get
            {
                return _blob;
            }
            set
            {
                _blob = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Map
    {
        #region Private fields
        private LocalisedBlob[] _image;
        private LocalisedUri[] _referenceWMS;
        private LegendEntry[] _otherLegend;
        private CoordType _min;
        private CoordType _max;
        private string _layerIndex;
        private double _layerOpacity;
        private extensions _extensions;
        #endregion

        public Map()
        {
            _extensions = new extensions();
            _max = new CoordType();
            _min = new CoordType();
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedBlob[] Image
        {
            get
            {
                return _image;
            }
            set
            {
                _image = value;
            }
        }

        [XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedUri[] ReferenceWMS
        {
            get
            {
                return _referenceWMS;
            }
            set
            {
                _referenceWMS = value;
            }
        }

        [XmlElement("OtherLegend")]
        public LegendEntry[] OtherLegend
        {
            get
            {
                return _otherLegend;
            }
            set
            {
                _otherLegend = value;
            }
        }

        public CoordType min
        {
            get
            {
                return _min;
            }
            set
            {
                _min = value;
            }
        }

        public CoordType max
        {
            get
            {
                return _max;
            }
            set
            {
                _max = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string layerIndex
        {
            get
            {
                return _layerIndex;
            }
            set
            {
                _layerIndex = value;
            }
        }

        public double layerOpacity
        {
            get
            {
                return _layerOpacity;
            }
            set
            {
                _layerOpacity = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class CoordType : GeometryType
    {
        #region Private fields
        private double _c1;
        private double _c2;
        private double _c3;
        #endregion

        [XmlElement(Order = 0)]
        public double c1
        {
            get
            {
                return _c1;
            }
            set
            {
                _c1 = value;
            }
        }

        [XmlElement(Order = 1)]
        public double c2
        {
            get
            {
                return _c2;
            }
            set
            {
                _c2 = value;
            }
        }

        [XmlElement(Order = 2)]
        public double c3
        {
            get
            {
                return _c3;
            }
            set
            {
                _c3 = value;
            }
        }
    }

    [XmlIncludeAttribute(typeof(SurfaceType))]
    [XmlIncludeAttribute(typeof(PolylineType))]
    [XmlIncludeAttribute(typeof(CoordType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public abstract partial class GeometryType
    {
        #region Private fields
        private extensions1 _extensions;
        private string _epsg;
        private System.Xml.XmlAttribute[] _anyAttr;
        #endregion

        public GeometryType()
        {
            _extensions = new extensions1();
        }

        [XmlElement(Order = 0)]
        public extensions1 extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }

        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string epsg
        {
            get
            {
                return _epsg;
            }
            set
            {
                _epsg = value;
            }
        }

        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return _anyAttr;
            }
            set
            {
                _anyAttr = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class extensions1
    {
        #region Private fields
        private System.Xml.XmlElement[] _any;
        #endregion

        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class SurfaceType : GeometryType
    {
        #region Private fields
        private BoundaryType[] _exterior;
        private BoundaryType[] _interior;
        #endregion

        [XmlElement("exterior", Order = 0)]
        public BoundaryType[] exterior
        {
            get
            {
                return _exterior;
            }
            set
            {
                _exterior = value;
            }
        }

        [XmlElement("interior", Order = 1)]
        public BoundaryType[] interior
        {
            get
            {
                return _interior;
            }
            set
            {
                _interior = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class BoundaryType
    {
        #region Private fields
        private PolylineType _polyline;
        #endregion

        public BoundaryType()
        {
            _polyline = new PolylineType();
        }

        public PolylineType polyline
        {
            get
            {
                return _polyline;
            }
            set
            {
                _polyline = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class PolylineType : GeometryType
    {
        #region Private fields
        private CoordType _coord;
        private object[] _items;
        #endregion

        public PolylineType()
        {
            _coord = new CoordType();
        }

        [XmlElement(Order = 0)]
        public CoordType coord
        {
            get
            {
                return _coord;
            }
            set
            {
                _coord = value;
            }
        }

        [XmlElement("arc", typeof(ArcSegmentType), Order = 1)]
        [XmlElement("coord", typeof(CoordType), Order = 1)]
        [XmlElement("customLineSegment", typeof(LineSegmentType), Order = 1)]
        public object[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class ArcSegmentType : LineSegmentType
    {
        #region Private fields
        private double _a1;
        private double _a2;
        private double _r;
        #endregion

        public double a1
        {
            get
            {
                return _a1;
            }
            set
            {
                _a1 = value;
            }
        }

        public double a2
        {
            get
            {
                return _a2;
            }
            set
            {
                _a2 = value;
            }
        }

        public double r
        {
            get
            {
                return _r;
            }
            set
            {
                _r = value;
            }
        }
    }

    [XmlIncludeAttribute(typeof(ArcSegmentType))]
    [XmlIncludeAttribute(typeof(StraightSegmentType))]
    [XmlIncludeAttribute(typeof(StartSegmentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public abstract partial class LineSegmentType
    {
        #region Private fields
        private extensions1 _extensions;
        private double _c1;
        private double _c2;
        private double _c3;
        private System.Xml.XmlAttribute[] _anyAttr;
        #endregion

        public LineSegmentType()
        {
            _extensions = new extensions1();
        }

        public extensions1 extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }

        public double c1
        {
            get
            {
                return _c1;
            }
            set
            {
                _c1 = value;
            }
        }

        public double c2
        {
            get
            {
                return _c2;
            }
            set
            {
                _c2 = value;
            }
        }

        public double c3
        {
            get
            {
                return _c3;
            }
            set
            {
                _c3 = value;
            }
        }

        [XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return _anyAttr;
            }
            set
            {
                _anyAttr = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class StraightSegmentType : LineSegmentType
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class StartSegmentType : LineSegmentType
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Geometry
    {
        #region Private fields
        private GeometryType _item;
        private Lawstatus _lawstatus;
        private string _metadataOfGeographicalBaseData;
        private extensions _extensions;
        #endregion

        public Geometry()
        {
            _extensions = new extensions();
            _lawstatus = new Lawstatus();
        }

        [XmlElement("Line", typeof(PolylineType))]
        [XmlElement("Point", typeof(CoordType))]
        [XmlElement("Surface", typeof(SurfaceType))]
        public GeometryType Item
        {
            get
            {
                return _item;
            }
            set
            {
                _item = value;
            }
        }

        public Lawstatus Lawstatus
        {
            get
            {
                return _lawstatus;
            }
            set
            {
                _lawstatus = value;
            }
        }

        [XmlElement(DataType = "anyURI")]
        public string MetadataOfGeographicalBaseData
        {
            get
            {
                return _metadataOfGeographicalBaseData;
            }
            set
            {
                _metadataOfGeographicalBaseData = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class RestrictionOnLandownership
    {
        #region Private fields
        private LocalisedMText[] _legendText;
        private Theme _theme;
        private string _typeCode;
        private string _typeCodelist;
        private Lawstatus _lawstatus;
        private string _areaShare;
        private decimal _partInPercent;
        private string _lengthShare;
        private string _nrOfPoints;
        private object _item;
        private Geometry[] _geometry;
        private Map _map;
        private Document[] _legalProvisions;
        private Office _responsibleOffice;
        private extensions _extensions;
        #endregion

        public RestrictionOnLandownership()
        {
            _extensions = new extensions();
            _responsibleOffice = new Office();
            _map = new Map();
            _lawstatus = new Lawstatus();
            _theme = new Theme();
        }

        [XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedMText[] LegendText
        {
            get
            {
                return _legendText;
            }
            set
            {
                _legendText = value;
            }
        }

        public Theme Theme
        {
            get
            {
                return _theme;
            }
            set
            {
                _theme = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string TypeCode
        {
            get
            {
                return _typeCode;
            }
            set
            {
                _typeCode = value;
            }
        }

        [XmlElement(DataType = "anyURI")]
        public string TypeCodelist
        {
            get
            {
                return _typeCodelist;
            }
            set
            {
                _typeCodelist = value;
            }
        }

        public Lawstatus Lawstatus
        {
            get
            {
                return _lawstatus;
            }
            set
            {
                _lawstatus = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string AreaShare
        {
            get
            {
                return _areaShare;
            }
            set
            {
                _areaShare = value;
            }
        }

        public decimal PartInPercent
        {
            get
            {
                return _partInPercent;
            }
            set
            {
                _partInPercent = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string LengthShare
        {
            get
            {
                return _lengthShare;
            }
            set
            {
                _lengthShare = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string NrOfPoints
        {
            get
            {
                return _nrOfPoints;
            }
            set
            {
                _nrOfPoints = value;
            }
        }

        [XmlElement("Symbol", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("SymbolRef", typeof(string), DataType = "anyURI")]
        public object Item
        {
            get
            {
                return _item;
            }
            set
            {
                _item = value;
            }
        }

        [XmlElement("Geometry")]
        public Geometry[] Geometry
        {
            get
            {
                return _geometry;
            }
            set
            {
                _geometry = value;
            }
        }

        public Map Map
        {
            get
            {
                return _map;
            }
            set
            {
                _map = value;
            }
        }

        [XmlElement("LegalProvisions")]
        public Document[] LegalProvisions
        {
            get
            {
                return _legalProvisions;
            }
            set
            {
                _legalProvisions = value;
            }
        }

        public Office ResponsibleOffice
        {
            get
            {
                return _responsibleOffice;
            }
            set
            {
                _responsibleOffice = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.interlis.ch/geometry/1.0")]
    public partial class MultiSurfaceType
    {
        #region Private fields
        private SurfaceType _surface;
        #endregion

        public MultiSurfaceType()
        {
            _surface = new SurfaceType();
        }

        public SurfaceType surface
        {
            get
            {
                return _surface;
            }
            set
            {
                _surface = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class RealEstateType
    {
        #region Private fields
        private RealEstateTypeCode _code;
        private LocalisedText[] _text;
        #endregion

        public RealEstateTypeCode Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum RealEstateTypeCode
    {
        RealEstate,
        [XmlEnumAttribute("Distinct_and_permanent_rights.BuildingRight")]
        Distinct_and_permanent_rightsBuildingRight,
        [XmlEnumAttribute("Distinct_and_permanent_rights.right_to_spring_water")]
        Distinct_and_permanent_rightsright_to_spring_water,
        [XmlEnumAttribute("Distinct_and_permanent_rights.concession")]
        Distinct_and_permanent_rightsconcession,
        [XmlEnumAttribute("Distinct_and_permanent_rights.other")]
        Distinct_and_permanent_rightsother,
        Mineral_rights,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class RealEstate_DPR
    {
        #region Private fields
        private string _number;
        private string _identDN;
        private string _eGRID;
        private RealEstateType _type;
        private CantonCode _canton;
        private string _municipalityName;
        private string _municipalityCode;
        private string _subunitOfLandRegister;
        private string _subunitOfLandRegisterDesignation;
        private string _metadataOfGeographicalBaseData;
        private string _landRegistryArea;
        private MultiSurfaceType _limit;
        private RestrictionOnLandownership[] _restrictionOnLandownership;
        private Map _planForLandRegister;
        private Map _planForLandRegisterMainPage;
        private extensions _extensions;
        #endregion

        public RealEstate_DPR()
        {
            _extensions = new extensions();
            _planForLandRegisterMainPage = new Map();
            _planForLandRegister = new Map();
            _limit = new MultiSurfaceType();
            _type = new RealEstateType();
        }

        [XmlElement(DataType = "normalizedString")]
        public string Number
        {
            get
            {
                return _number;
            }
            set
            {
                _number = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string IdentDN
        {
            get
            {
                return _identDN;
            }
            set
            {
                _identDN = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string EGRID
        {
            get
            {
                return _eGRID;
            }
            set
            {
                _eGRID = value;
            }
        }

        public RealEstateType Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        public CantonCode Canton
        {
            get
            {
                return _canton;
            }
            set
            {
                _canton = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string MunicipalityName
        {
            get
            {
                return _municipalityName;
            }
            set
            {
                _municipalityName = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string MunicipalityCode
        {
            get
            {
                return _municipalityCode;
            }
            set
            {
                _municipalityCode = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string SubunitOfLandRegister
        {
            get
            {
                return _subunitOfLandRegister;
            }
            set
            {
                _subunitOfLandRegister = value;
            }
        }

        [XmlElement(DataType = "normalizedString")]
        public string SubunitOfLandRegisterDesignation
        {
            get
            {
                return _subunitOfLandRegisterDesignation;
            }
            set
            {
                _subunitOfLandRegisterDesignation = value;
            }
        }

        [XmlElement(DataType = "anyURI")]
        public string MetadataOfGeographicalBaseData
        {
            get
            {
                return _metadataOfGeographicalBaseData;
            }
            set
            {
                _metadataOfGeographicalBaseData = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string LandRegistryArea
        {
            get
            {
                return _landRegistryArea;
            }
            set
            {
                _landRegistryArea = value;
            }
        }

        public MultiSurfaceType Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _limit = value;
            }
        }

        [XmlElement("RestrictionOnLandownership")]
        public RestrictionOnLandownership[] RestrictionOnLandownership
        {
            get
            {
                return _restrictionOnLandownership;
            }
            set
            {
                _restrictionOnLandownership = value;
            }
        }

        public Map PlanForLandRegister
        {
            get
            {
                return _planForLandRegister;
            }
            set
            {
                _planForLandRegister = value;
            }
        }

        public Map PlanForLandRegisterMainPage
        {
            get
            {
                return _planForLandRegisterMainPage;
            }
            set
            {
                _planForLandRegisterMainPage = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public enum CantonCode
    {
        ZH,
        BE,
        LU,
        UR,
        SZ,
        OW,
        NW,
        GL,
        ZG,
        FR,
        SO,
        BS,
        BL,
        SH,
        AR,
        AI,
        SG,
        GR,
        AG,
        TG,
        TI,
        VD,
        VS,
        NE,
        GE,
        JU,
        FL,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/ExtractData")]
    public partial class Glossary
    {
        #region Private fields
        private LocalisedText[] _title;
        private LocalisedMText[] _content;
        private extensions _extensions;
        #endregion

        public Glossary()
        {
            _extensions = new extensions();
        }

        [XmlArrayItemAttribute(IsNullable = false)]
        public LocalisedText[] Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }

        [XmlArrayItemAttribute("LocalisedText", IsNullable = false)]
        public LocalisedMText[] Content
        {
            get
            {
                return _content;
            }
            set
            {
                _content = value;
            }
        }

        public extensions extensions
        {
            get
            {
                return _extensions;
            }
            set
            {
                _extensions = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/Extract")]
    [XmlRootAttribute("GetEGRIDResponse", Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/Extract", IsNullable = false)]
    public partial class GetEGRIDResponseType
    {
        #region Private fields
        private string _egrid;
        private string _number;
        private string _identDN;
        private RealEstateType _type;
        private MultiSurfaceType _limit;
        #endregion

        [XmlElement("egrid", DataType = "token")]
        public string egrid
        {
            get
            {
                return _egrid;
            }
            set
            {
                _egrid = value;
            }
        }

        [XmlElement("number", DataType = "token")]
        public string number
        {
            get
            {
                return _number;
            }
            set
            {
                _number = value;
            }
        }

        [XmlElement("identDN", DataType = "token")]
        public string identDN
        {
            get
            {
                return _identDN;
            }
            set
            {
                _identDN = value;
            }
        }

        [XmlElement("type")]
        public RealEstateType type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        [XmlElement("limit")]
        public MultiSurfaceType limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _limit = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/Extract")]
    [XmlRootAttribute("GetCapabilitiesResponse", Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/2.0/Extract", IsNullable = false)]
    public partial class GetCapabilitiesResponseType
    {
        #region Private fields
        private Theme[] _topic;
        private string[] _municipality;
        private string[] _flavour;
        private string[] _language;
        private string[] _crs;
        #endregion

        [XmlElement("topic")]
        public Theme[] topic
        {
            get
            {
                return _topic;
            }
            set
            {
                _topic = value;
            }
        }

        [XmlElement("municipality", DataType = "integer")]
        public string[] municipality
        {
            get
            {
                return _municipality;
            }
            set
            {
                _municipality = value;
            }
        }

        [XmlElement("flavour", DataType = "token")]
        public string[] flavour
        {
            get
            {
                return _flavour;
            }
            set
            {
                _flavour = value;
            }
        }

        [XmlElement("language", DataType = "token")]
        public string[] language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        [XmlElement("crs", DataType = "token")]
        public string[] crs
        {
            get
            {
                return _crs;
            }
            set
            {
                _crs = value;
            }
        }
    }
}
#pragma warning restore
