/* $Rev: 14634 $ */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using DataExtract.Extract;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract")]
[System.Xml.Serialization.XmlRootAttribute("GetExtractByIdResponse", Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract", IsNullable=false)]
public partial class GetExtractByIdResponseType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("embeddable", typeof(GetExtractByIdResponseTypeEmbeddable))]
    [System.Xml.Serialization.XmlElementAttribute("Extract", typeof(Extract), Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/ExtractData")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract")]
public partial class GetExtractByIdResponseTypeEmbeddable {
    
    private System.DateTime cadasterStateField;
    
    private string cadasterOrganisationNameField;
    
    private string dataownerNameCadastralSurveyingField;
    
    private System.DateTime transferFromSourceCadastralSurveyingField;
    
    private GetExtractByIdResponseTypeEmbeddableDatasource datasourceField;
    
    private byte[] pdfField;
    
    /// <remarks/>
    public System.DateTime cadasterState {
        get {
            return this.cadasterStateField;
        }
        set {
            this.cadasterStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string cadasterOrganisationName {
        get {
            return this.cadasterOrganisationNameField;
        }
        set {
            this.cadasterOrganisationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string dataownerNameCadastralSurveying {
        get {
            return this.dataownerNameCadastralSurveyingField;
        }
        set {
            this.dataownerNameCadastralSurveyingField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime transferFromSourceCadastralSurveying {
        get {
            return this.transferFromSourceCadastralSurveyingField;
        }
        set {
            this.transferFromSourceCadastralSurveyingField = value;
        }
    }
    
    /// <remarks/>
    public GetExtractByIdResponseTypeEmbeddableDatasource datasource {
        get {
            return this.datasourceField;
        }
        set {
            this.datasourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] pdf {
        get {
            return this.pdfField;
        }
        set {
            this.pdfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract")]
public partial class GetExtractByIdResponseTypeEmbeddableDatasource {
    
    private Theme topicField;
    
    private string dataownerNameField;
    
    private System.DateTime transferFromSourceField;
    
    /// <remarks/>
    public Theme topic {
        get {
            return this.topicField;
        }
        set {
            this.topicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string dataownerName {
        get {
            return this.dataownerNameField;
        }
        set {
            this.dataownerNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime transferFromSource {
        get {
            return this.transferFromSourceField;
        }
        set {
            this.transferFromSourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract")]
[System.Xml.Serialization.XmlRootAttribute("GetEGRIDResponse", Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract", IsNullable=false)]
public partial class GetEGRIDResponseType {
    
    private string[] egridField;
    
    private string[] numberField;
    
    private string[] identDNField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("egrid", DataType="token")]
    public string[] egrid {
        get {
            return this.egridField;
        }
        set {
            this.egridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("number", DataType="token")]
    public string[] number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identDN", DataType="token")]
    public string[] identDN {
        get {
            return this.identDNField;
        }
        set {
            this.identDNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract")]
[System.Xml.Serialization.XmlRootAttribute("GetCapabilitiesResponse", Namespace="http://schemas.geo.admin.ch/swisstopo/OeREBK/15/Extract", IsNullable=false)]
public partial class GetCapabilitiesResponseType {
    
    private Theme[] topicField;
    
    private string[] municipalityField;
    
    private string[] flavourField;
    
    private string[] languageField;
    
    private string[] crsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("topic")]
    public Theme[] topic {
        get {
            return this.topicField;
        }
        set {
            this.topicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("municipality", DataType="integer")]
    public string[] municipality {
        get {
            return this.municipalityField;
        }
        set {
            this.municipalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("flavour", DataType="token")]
    public string[] flavour {
        get {
            return this.flavourField;
        }
        set {
            this.flavourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("language", DataType="token")]
    public string[] language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("crs", DataType="token")]
    public string[] crs {
        get {
            return this.crsField;
        }
        set {
            this.crsField = value;
        }
    }
}
