/* $Rev: 29789 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net45","NameSpace":"OeREBKRMkvs_V2_0","CollectionObjectType":"Array","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace OeREBKRMkvs_V2_0
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;    

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0Thema
    {
        #region Private fields
        private object[] _items;
        private string _bID;
        #endregion

        [XmlElement("OeREBKRMkvs_V2_0.Thema.Thema", typeof(TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThema))]
        [XmlElement("OeREBKRMkvs_V2_0.Thema.ThemaGesetz", typeof(TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetz))]
        public object[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        [XmlAttribute]
        public string BID
        {
            get
            {
                return _bID;
            }
            set
            {
                _bID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThema
    {
        #region Private fields
        private string _code;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitel _titel;
        private ushort _auszugIndex;
        private string _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThema()
        {
            _titel = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitel();
        }

        public string Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        public ushort AuszugIndex
        {
            get
            {
                return _auszugIndex;
            }
            set
            {
                _auszugIndex = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitel
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitelLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitel()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitelLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitelLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaTitelLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetz
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzThema _thema;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzGesetz _gesetz;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetz()
        {
            _gesetz = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzGesetz();
            _thema = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzThema();
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzThema Thema
        {
            get
            {
                return _thema;
            }
            set
            {
                _thema = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzGesetz Gesetz
        {
            get
            {
                return _gesetz;
            }
            set
            {
                _gesetz = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzThema
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0ThemaOeREBKRMkvs_V2_0ThemaThemaGesetzGesetz
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }
}
#pragma warning restore
