/* $Rev: 29789 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net45","NameSpace":"OeREBKRMkvs_V2_0","CollectionObjectType":"Array","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace OeREBKRMkvs_V2_0
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using OeREBKRMtrsfr_V2_0;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRM_V2_0Dokumente
    {
        #region Private fields
        private Dokument[] _oeREBKRM_V2_0DokumenteDokument;
        private TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmt _oeREBKRM_V2_0AmtAmt;
        private string _bID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRM_V2_0Dokumente()
        {
            _oeREBKRM_V2_0AmtAmt = new TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmt();
        }

        [XmlElement("OeREBKRM_V2_0.Dokumente.Dokument")]
        public Dokument[] OeREBKRM_V2_0DokumenteDokument
        {
            get
            {
                return _oeREBKRM_V2_0DokumenteDokument;
            }
            set
            {
                _oeREBKRM_V2_0DokumenteDokument = value;
            }
        }

        [XmlElement("OeREBKRM_V2_0.Amt.Amt")]
        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmt OeREBKRM_V2_0AmtAmt
        {
            get
            {
                return _oeREBKRM_V2_0AmtAmt;
            }
            set
            {
                _oeREBKRM_V2_0AmtAmt = value;
            }
        }

        [XmlAttribute]
        public string BID
        {
            get
            {
                return _bID;
            }
            set
            {
                _bID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmt
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtName _name;
        private TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWeb _amtImWeb;
        private string _uID;
        private string _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmt()
        {
            _amtImWeb = new TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWeb();
            _name = new TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtName();
        }

        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtName Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWeb AmtImWeb
        {
            get
            {
                return _amtImWeb;
            }
            set
            {
                _amtImWeb = value;
            }
        }

        public string UID
        {
            get
            {
                return _uID;
            }
            set
            {
                _uID = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtName
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtNameLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtName()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtNameLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtNameLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtNameLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWeb
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWebOeREBKRM_V2_0MultilingualUri _oeREBKRM_V2_0MultilingualUri;
        #endregion

        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWeb()
        {
            _oeREBKRM_V2_0MultilingualUri = new TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWebOeREBKRM_V2_0MultilingualUri();
        }

        [XmlElement("OeREBKRM_V2_0.MultilingualUri")]
        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWebOeREBKRM_V2_0MultilingualUri OeREBKRM_V2_0MultilingualUri
        {
            get
            {
                return _oeREBKRM_V2_0MultilingualUri;
            }
            set
            {
                _oeREBKRM_V2_0MultilingualUri = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWebOeREBKRM_V2_0MultilingualUri
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWebOeREBKRM_V2_0MultilingualUriOeREBKRM_V2_0LocalisedUri[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("OeREBKRM_V2_0.LocalisedUri", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWebOeREBKRM_V2_0MultilingualUriOeREBKRM_V2_0LocalisedUri[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRM_V2_0DokumenteOeREBKRM_V2_0AmtAmtAmtImWebOeREBKRM_V2_0MultilingualUriOeREBKRM_V2_0LocalisedUri
    {
        #region Private fields
        private string _language;
        private string _text;
        #endregion

        public string Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }
}
#pragma warning restore
