/* $Rev: 29789 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net45","NameSpace":"zivilflugplaetze_v2_0","CollectionObjectType":"Array","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace OeREBKRMtrsfr_V2_0
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    [XmlRootAttribute(Namespace = "http://www.interlis.ch/INTERLIS2.3", IsNullable = false)]
    public partial class TRANSFER
    {
        #region Private fields
        private TRANSFERHEADERSECTION _hEADERSECTION;
        private TRANSFERDATASECTION _dATASECTION;
        #endregion

        public TRANSFER()
        {
            _dATASECTION = new TRANSFERDATASECTION();
            _hEADERSECTION = new TRANSFERHEADERSECTION();
        }

        public TRANSFERHEADERSECTION HEADERSECTION
        {
            get
            {
                return _hEADERSECTION;
            }
            set
            {
                _hEADERSECTION = value;
            }
        }

        public TRANSFERDATASECTION DATASECTION
        {
            get
            {
                return _dATASECTION;
            }
            set
            {
                _dATASECTION = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERHEADERSECTION
    {
        #region Private fields
        private TRANSFERHEADERSECTIONMODEL[] _mODELS;
        private string _sENDER;
        private decimal _vERSION;
        #endregion

        [XmlArrayItemAttribute("MODEL", IsNullable = false)]
        public TRANSFERHEADERSECTIONMODEL[] MODELS
        {
            get
            {
                return _mODELS;
            }
            set
            {
                _mODELS = value;
            }
        }

        [XmlAttribute]
        public string SENDER
        {
            get
            {
                return _sENDER;
            }
            set
            {
                _sENDER = value;
            }
        }

        [XmlAttribute]
        public decimal VERSION
        {
            get
            {
                return _vERSION;
            }
            set
            {
                _vERSION = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERHEADERSECTIONMODEL
    {
        #region Private fields
        private string _nAME;
        private System.DateTime _vERSION;
        private string _uRI;
        #endregion

        [XmlAttribute]
        public string NAME
        {
            get
            {
                return _nAME;
            }
            set
            {
                _nAME = value;
            }
        }

        [XmlAttribute(DataType = "date")]
        public System.DateTime VERSION
        {
            get
            {
                return _vERSION;
            }
            set
            {
                _vERSION = value;
            }
        }

        [XmlAttribute]
        public string URI
        {
            get
            {
                return _uRI;
            }
            set
            {
                _uRI = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTION
    {
        #region Private fields
        private Transferstruktur _oeREBKRMtrsfr_V2_0Transferstruktur;
        #endregion

        public TRANSFERDATASECTION()
        {
            _oeREBKRMtrsfr_V2_0Transferstruktur = new Transferstruktur();
        }

        [XmlElement("OeREBKRMtrsfr_V2_0.Transferstruktur")]
        public Transferstruktur OeREBKRMtrsfr_V2_0Transferstruktur
        {
            get
            {
                return _oeREBKRMtrsfr_V2_0Transferstruktur;
            }
            set
            {
                _oeREBKRMtrsfr_V2_0Transferstruktur = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Transferstruktur
    {
        #region Private fields
        private object[] _items;
        private string _bID;
        #endregion

        [XmlElement("OeREBKRM_V2_0.Amt.Amt", typeof(Amt))]
        [XmlElement("OeREBKRM_V2_0.Dokumente.Dokument", typeof(Dokument))]
        [XmlElement("OeREBKRMtrsfr_V2_0.Transferstruktur.DarstellungsDienst", typeof(DarstellungsDienst))]
        [XmlElement("OeREBKRMtrsfr_V2_0.Transferstruktur.Eigentumsbeschraenkung", typeof(Eigentumsbeschraenkung))]
        [XmlElement("OeREBKRMtrsfr_V2_0.Transferstruktur.Geometrie", typeof(Geometrie))]
        [XmlElement("OeREBKRMtrsfr_V2_0.Transferstruktur.HinweisVorschrift", typeof(HinweisVorschrift))]
        [XmlElement("OeREBKRMtrsfr_V2_0.Transferstruktur.LegendeEintrag", typeof(LegendeEintrag))]
        public object[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        [XmlAttribute]
        public string BID
        {
            get
            {
                return _bID;
            }
            set
            {
                _bID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Amt
    {
        #region Private fields
        private AmtName _name;
        private AmtImWeb _amtImWeb;
        private string _zeile1;
        private string _zeile2;
        private string _strasse;
        private string _hausnr;
        private string _pLZ;
        private string _ort;
        private string _uID;
        private string _tID;
        #endregion

        public Amt()
        {
            _amtImWeb = new AmtImWeb();
            _name = new AmtName();
        }

        public AmtName Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        public AmtImWeb AmtImWeb
        {
            get
            {
                return _amtImWeb;
            }
            set
            {
                _amtImWeb = value;
            }
        }

        public string Zeile1
        {
            get
            {
                return _zeile1;
            }
            set
            {
                _zeile1 = value;
            }
        }

        public string Zeile2
        {
            get
            {
                return _zeile2;
            }
            set
            {
                _zeile2 = value;
            }
        }

        public string Strasse
        {
            get
            {
                return _strasse;
            }
            set
            {
                _strasse = value;
            }
        }

        public string Hausnr
        {
            get
            {
                return _hausnr;
            }
            set
            {
                _hausnr = value;
            }
        }

        public string PLZ
        {
            get
            {
                return _pLZ;
            }
            set
            {
                _pLZ = value;
            }
        }

        public string Ort
        {
            get
            {
                return _ort;
            }
            set
            {
                _ort = value;
            }
        }


        public string UID
        {
            get
            {
                return _uID;
            }
            set
            {
                _uID = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class AmtName
    {
        #region Private fields
        private MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public AmtName()
        {
            _localisationCH_V1MultilingualText = new MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class MultilingualText
    {
        #region Private fields
        private LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class LocalisedText
    {
        #region Private fields
        private string _language;
        private string _text;
        #endregion

        public string Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class AmtImWeb
    {
        #region Private fields
        private MultilingualUri _oeREBKRM_V2_0MultilingualUri;
        #endregion

        public AmtImWeb()
        {
            _oeREBKRM_V2_0MultilingualUri = new MultilingualUri();
        }

        [XmlElement("OeREBKRM_V2_0.MultilingualUri")]
        public MultilingualUri OeREBKRM_V2_0MultilingualUri
        {
            get
            {
                return _oeREBKRM_V2_0MultilingualUri;
            }
            set
            {
                _oeREBKRM_V2_0MultilingualUri = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class MultilingualUri
    {
        #region Private fields
        private LocalisedUri[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("OeREBKRM_V2_0.LocalisedUri", IsNullable = false)]
        public LocalisedUri[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class LocalisedUri
    {
        #region Private fields
        private string _language;
        private string _text;
        #endregion

        public string Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Dokument
    {
        #region Private fields
        private string _typ;
        private DokumentTitel _titel;
        private DokumentAbkuerzung _abkuerzung;
        private DokumentOffizielleNr _offizielleNr;
        private DokumentTextImWeb _textImWeb;
        private string _auszugIndex;
        private string _rechtsstatus;
        private System.DateTime _publiziertAb;
        private ZustaendigeStelle _zustaendigeStelle;
        private string _tID;
        #endregion

        public Dokument()
        {
            _zustaendigeStelle = new ZustaendigeStelle();
            _textImWeb = new DokumentTextImWeb();
            _titel = new DokumentTitel();
        }

        public string Typ
        {
            get
            {
                return _typ;
            }
            set
            {
                _typ = value;
            }
        }

        public DokumentTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        public DokumentTextImWeb TextImWeb
        {
            get
            {
                return _textImWeb;
            }
            set
            {
                _textImWeb = value;
            }
        }

        public DokumentAbkuerzung Abkuerzung
        {
            get
            {
                return _abkuerzung;
            }
            set
            {
                _abkuerzung = value;
            }
        }

        public DokumentOffizielleNr OffizielleNr
        {
            get
            {
                return _offizielleNr;
            }
            set
            {
                _offizielleNr = value;
            }
        }

        public string AuszugIndex
        {
            get
            {
                return _auszugIndex;
            }
            set
            {
                _auszugIndex = value;
            }
        }

        public string Rechtsstatus
        {
            get
            {
                return _rechtsstatus;
            }
            set
            {
                _rechtsstatus = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime publiziertAb
        {
            get
            {
                return _publiziertAb;
            }
            set
            {
                _publiziertAb = value;
            }
        }

        public ZustaendigeStelle ZustaendigeStelle
        {
            get
            {
                return _zustaendigeStelle;
            }
            set
            {
                _zustaendigeStelle = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class DokumentTitel
    {
        #region Private fields
        private MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public DokumentTitel()
        {
            _localisationCH_V1MultilingualText = new MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class DokumentAbkuerzung
    {
        #region Private fields
        private MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public DokumentAbkuerzung()
        {
            _localisationCH_V1MultilingualText = new MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class DokumentOffizielleNr
    {
        #region Private fields
        private MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public DokumentOffizielleNr()
        {
            _localisationCH_V1MultilingualText = new MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class DokumentTextImWeb
    {
        #region Private fields
        private MultilingualUri _oeREBKRM_V2_0MultilingualUri;
        #endregion

        public DokumentTextImWeb()
        {
            _oeREBKRM_V2_0MultilingualUri = new MultilingualUri();
        }

        [XmlElement("OeREBKRM_V2_0.MultilingualUri")]
        public MultilingualUri OeREBKRM_V2_0MultilingualUri
        {
            get
            {
                return _oeREBKRM_V2_0MultilingualUri;
            }
            set
            {
                _oeREBKRM_V2_0MultilingualUri = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class ZustaendigeStelle
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class DarstellungsDienst
    {
        #region Private fields
        private VerweisWMS _verweisWMS;
        private string _tID;
        #endregion

        public DarstellungsDienst()
        {
            _verweisWMS = new VerweisWMS();
        }

        public VerweisWMS VerweisWMS
        {
            get
            {
                return _verweisWMS;
            }
            set
            {
                _verweisWMS = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class VerweisWMS
    {
        #region Private fields
        private MultilingualUri _oeREBKRM_V2_0MultilingualUri;
        #endregion

        public VerweisWMS()
        {
            _oeREBKRM_V2_0MultilingualUri = new MultilingualUri();
        }

        [XmlElement("OeREBKRM_V2_0.MultilingualUri")]
        public MultilingualUri OeREBKRM_V2_0MultilingualUri
        {
            get
            {
                return _oeREBKRM_V2_0MultilingualUri;
            }
            set
            {
                _oeREBKRM_V2_0MultilingualUri = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Eigentumsbeschraenkung
    {
        #region Private fields
        private string _rechtsstatus;
        private System.DateTime _publiziertAb;
        private EigentumsbeschraenkungDarstellungsDienst _darstellungsDienst;
        private Legende _legende;
        private EigentumsbeschraenkungZustaendigeStelle _zustaendigeStelle;
        private string _tID;
        #endregion

        public Eigentumsbeschraenkung()
        {
            _zustaendigeStelle = new EigentumsbeschraenkungZustaendigeStelle();
            _legende = new Legende();
            _darstellungsDienst = new EigentumsbeschraenkungDarstellungsDienst();
        }

        public string Rechtsstatus
        {
            get
            {
                return _rechtsstatus;
            }
            set
            {
                _rechtsstatus = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime publiziertAb
        {
            get
            {
                return _publiziertAb;
            }
            set
            {
                _publiziertAb = value;
            }
        }

        public EigentumsbeschraenkungDarstellungsDienst DarstellungsDienst
        {
            get
            {
                return _darstellungsDienst;
            }
            set
            {
                _darstellungsDienst = value;
            }
        }

        public Legende Legende
        {
            get
            {
                return _legende;
            }
            set
            {
                _legende = value;
            }
        }

        public EigentumsbeschraenkungZustaendigeStelle ZustaendigeStelle
        {
            get
            {
                return _zustaendigeStelle;
            }
            set
            {
                _zustaendigeStelle = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class EigentumsbeschraenkungDarstellungsDienst
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Legende
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class EigentumsbeschraenkungZustaendigeStelle
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Geometrie
    {
        #region Private fields
        private Flaeche _flaeche;
        private Linie _linie;
        private Punkt _punkt;
        private string _rechtsstatus;
        private System.DateTime _publiziertAb;
        private string _metadatenGeobasisdaten;
        private GeometrieEigentumsbeschraenkung _eigentumsbeschraenkung;
        private string _tID;
        #endregion

        public Geometrie()
        {
            _eigentumsbeschraenkung = new GeometrieEigentumsbeschraenkung();
            _punkt = new Punkt();
            _linie = new Linie();
            _flaeche = new Flaeche();
        }

        public Flaeche Flaeche
        {
            get
            {
                return _flaeche;
            }
            set
            {
                _flaeche = value;
            }
        }

        public Linie Linie
        {
            get
            {
                return _linie;
            }
            set
            {
                _linie = value;
            }
        }

        public Punkt Punkt
        {
            get
            {
                return _punkt;
            }
            set
            {
                _punkt = value;
            }
        }

        public string Rechtsstatus
        {
            get
            {
                return _rechtsstatus;
            }
            set
            {
                _rechtsstatus = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime publiziertAb
        {
            get
            {
                return _publiziertAb;
            }
            set
            {
                _publiziertAb = value;
            }
        }

        public string MetadatenGeobasisdaten
        {
            get
            {
                return _metadatenGeobasisdaten;
            }
            set
            {
                _metadatenGeobasisdaten = value;
            }
        }

        public GeometrieEigentumsbeschraenkung Eigentumsbeschraenkung
        {
            get
            {
                return _eigentumsbeschraenkung;
            }
            set
            {
                _eigentumsbeschraenkung = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Flaeche
    {
        #region Private fields
        private BOUNDARY[] _sURFACE;
        #endregion

        [XmlArrayItemAttribute("BOUNDARY", IsNullable = false)]
        public BOUNDARY[] SURFACE
        {
            get
            {
                return _sURFACE;
            }
            set
            {
                _sURFACE = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class BOUNDARY
    {
        #region Private fields
        private COORD[] _pOLYLINE;
        #endregion

        [XmlArrayItemAttribute("COORD", IsNullable = false)]
        public COORD[] POLYLINE
        {
            get
            {
                return _pOLYLINE;
            }
            set
            {
                _pOLYLINE = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class COORD
    {
        #region Private fields
        private decimal _c1;
        private decimal _c2;
        #endregion

        public decimal C1
        {
            get
            {
                return _c1;
            }
            set
            {
                _c1 = value;
            }
        }

        public decimal C2
        {
            get
            {
                return _c2;
            }
            set
            {
                _c2 = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Linie
    {
        #region Private fields
        private COORD[] _pOLYLINE;
        #endregion

        [XmlArrayItemAttribute("COORD", IsNullable = false)]
        public COORD[] POLYLINE
        {
            get
            {
                return _pOLYLINE;
            }
            set
            {
                _pOLYLINE = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Punkt
    {
        #region Private fields
        private COORD _cOORD;
        #endregion

        public Punkt()
        {
            _cOORD = new COORD();
        }

        [XmlElement("COORD")]
        public COORD PunktCOORD
        {
            get
            {
                return _cOORD;
            }
            set
            {
                _cOORD = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class GeometrieEigentumsbeschraenkung
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class HinweisVorschrift
    {
        #region Private fields
        private HinweisVorschriftEigentumsbeschraenkung _eigentumsbeschraenkung;
        private Vorschrift _vorschrift;
        #endregion

        public HinweisVorschrift()
        {
            _vorschrift = new Vorschrift();
            _eigentumsbeschraenkung = new HinweisVorschriftEigentumsbeschraenkung();
        }

        public HinweisVorschriftEigentumsbeschraenkung Eigentumsbeschraenkung
        {
            get
            {
                return _eigentumsbeschraenkung;
            }
            set
            {
                _eigentumsbeschraenkung = value;
            }
        }

        public Vorschrift Vorschrift
        {
            get
            {
                return _vorschrift;
            }
            set
            {
                _vorschrift = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class HinweisVorschriftEigentumsbeschraenkung
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class Vorschrift
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class LegendeEintrag
    {
        #region Private fields
        private LegendeEintragSymbol _symbol;
        private LegendeText _legendeText;
        private string _artCode;
        private string _artCodeliste;
        private string _thema;
        private LegendeEintragDarstellungsDienst _darstellungsDienst;
        private string _tID;
        #endregion

        public LegendeEintrag()
        {
            _darstellungsDienst = new LegendeEintragDarstellungsDienst();
            _legendeText = new LegendeText();
            _symbol = new LegendeEintragSymbol();
        }

        public LegendeEintragSymbol Symbol
        {
            get
            {
                return _symbol;
            }
            set
            {
                _symbol = value;
            }
        }

        public LegendeText LegendeText
        {
            get
            {
                return _legendeText;
            }
            set
            {
                _legendeText = value;
            }
        }

        public string ArtCode
        {
            get
            {
                return _artCode;
            }
            set
            {
                _artCode = value;
            }
        }

        public string ArtCodeliste
        {
            get
            {
                return _artCodeliste;
            }
            set
            {
                _artCodeliste = value;
            }
        }

        public string Thema
        {
            get
            {
                return _thema;
            }
            set
            {
                _thema = value;
            }
        }

        public LegendeEintragDarstellungsDienst DarstellungsDienst
        {
            get
            {
                return _darstellungsDienst;
            }
            set
            {
                _darstellungsDienst = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class LegendeEintragSymbol
    {
        #region Private fields
        private string _bINBLBOX;
        #endregion

        public string BINBLBOX
        {
            get
            {
                return _bINBLBOX;
            }
            set
            {
                _bINBLBOX = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class LegendeText
    {
        #region Private fields
        private MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public LegendeText()
        {
            _localisationCH_V1MultilingualText = new MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class LegendeEintragDarstellungsDienst
    {
        #region Private fields
        private string _rEF;
        #endregion

        [XmlAttribute]
        public string REF
        {
            get
            {
                return _rEF;
            }
            set
            {
                _rEF = value;
            }
        }
    }
}
#pragma warning restore
