/* $Rev: 29789 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net45","NameSpace":"OeREBKRMkvs_V2_0","CollectionObjectType":"Array","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace OeREBKRMkvs_V2_0
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0Konfiguration
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogo[] _oeREBKRMkvs_V2_0KonfigurationLogo;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt[] _oeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxt[] _oeREBKRMkvs_V2_0KonfigurationDokumentTypTxt;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt[] _oeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossar[] _oeREBKRMkvs_V2_0KonfigurationGlossar;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweis[] _oeREBKRMkvs_V2_0KonfigurationHaftungshinweis;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformation[] _oeREBKRMkvs_V2_0KonfigurationInformation;

        private string _bID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0Konfiguration()
        {

        }

        [XmlElement("OeREBKRMkvs_V2_0.Konfiguration.Logo")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogo[] OeREBKRMkvs_V2_0KonfigurationLogo
        {
            get
            {
                return _oeREBKRMkvs_V2_0KonfigurationLogo;
            }
            set
            {
                _oeREBKRMkvs_V2_0KonfigurationLogo = value;
            }
        }

        [XmlElement("OeREBKRMkvs_V2_0.Konfiguration.RechtsStatusTxt")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt[] OeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt
        {
            get
            {
                return _oeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt;
            }
            set
            {
                _oeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt = value;
            }
        }

        [XmlElement("OeREBKRMkvs_V2_0.Konfiguration.DokumentTypTxt")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxt[] OeREBKRMkvs_V2_0KonfigurationDokumentTypTxt
        {
            get
            {
                return _oeREBKRMkvs_V2_0KonfigurationDokumentTypTxt;
            }
            set
            {
                _oeREBKRMkvs_V2_0KonfigurationDokumentTypTxt = value;
            }
        }

        [XmlElement("OeREBKRMkvs_V2_0.Konfiguration.GrundstuecksArtTxt")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt[] OeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt
        {
            get
            {
                return _oeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt;
            }
            set
            {
                _oeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt = value;
            }
        }

        [XmlElement("OeREBKRMkvs_V2_0.Konfiguration.Glossar")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossar[] OeREBKRMkvs_V2_0KonfigurationGlossar
        {
            get
            {
                return _oeREBKRMkvs_V2_0KonfigurationGlossar;
            }
            set
            {
                _oeREBKRMkvs_V2_0KonfigurationGlossar = value;
            }
        }

        [XmlElement("OeREBKRMkvs_V2_0.Konfiguration.Haftungshinweis")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweis[] OeREBKRMkvs_V2_0KonfigurationHaftungshinweis
        {
            get
            {
                return _oeREBKRMkvs_V2_0KonfigurationHaftungshinweis;
            }
            set
            {
                _oeREBKRMkvs_V2_0KonfigurationHaftungshinweis = value;
            }
        }

        [XmlElement("OeREBKRMkvs_V2_0.Konfiguration.Information")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformation[] OeREBKRMkvs_V2_0KonfigurationInformation
        {
            get
            {
                return _oeREBKRMkvs_V2_0KonfigurationInformation;
            }
            set
            {
                _oeREBKRMkvs_V2_0KonfigurationInformation = value;
            }
        }

        [XmlAttribute]
        public string BID
        {
            get
            {
                return _bID;
            }
            set
            {
                _bID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogo
    {
        #region Private fields
        private string _code;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBild _bild;
        private string _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogo()
        {
            _bild = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBild();
        }

        public string Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBild Bild
        {
            get
            {
                return _bild;
            }
            set
            {
                _bild = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBild
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlob _oeREBKRM_V2_0MultilingualBlob;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBild()
        {
            _oeREBKRM_V2_0MultilingualBlob = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlob();
        }

        [XmlElement("OeREBKRM_V2_0.MultilingualBlob")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlob OeREBKRM_V2_0MultilingualBlob
        {
            get
            {
                return _oeREBKRM_V2_0MultilingualBlob;
            }
            set
            {
                _oeREBKRM_V2_0MultilingualBlob = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlob
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlob[] _localisedBlob;
        #endregion

        [XmlArrayItemAttribute("OeREBKRM_V2_0.LocalisedBlob", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlob[] LocalisedBlob
        {
            get
            {
                return _localisedBlob;
            }
            set
            {
                _localisedBlob = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlob
    {
        #region Private fields
        private string _language;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlobBlob _blob;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlob()
        {
            _blob = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlobBlob();
        }

        public string Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlobBlob Blob
        {
            get
            {
                return _blob;
            }
            set
            {
                _blob = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationLogoBildOeREBKRM_V2_0MultilingualBlobOeREBKRM_V2_0LocalisedBlobBlob
    {
        #region Private fields
        private string _bINBLBOX;
        #endregion

        public string BINBLBOX
        {
            get
            {
                return _bINBLBOX;
            }
            set
            {
                _bINBLBOX = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt
    {
        #region Private fields
        private string _code;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitel _titel;
        private byte _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxt()
        {
            _titel = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitel();
        }

        public string Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        [XmlAttribute]
        public byte TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitel
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitelLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitel()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitelLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitelLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationRechtsStatusTxtTitelLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText
    {
        #region Private fields
        private string _language;
        private string _text;
        #endregion

        public string Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxt
    {
        #region Private fields
        private string _code;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitel _titel;
        private byte _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxt()
        {
            _titel = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitel();
        }

        public string Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        [XmlAttribute]
        public byte TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitel
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitelLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitel()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitelLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitelLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationDokumentTypTxtTitelLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt
    {
        #region Private fields
        private string _code;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitel _titel;
        private byte _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxt()
        {
            _titel = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitel();
        }

        public string Code
        {
            get
            {
                return _code;
            }
            set
            {
                _code = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        [XmlAttribute]
        public byte TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitel
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitelLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitel()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitelLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitelLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGrundstuecksArtTxtTitelLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossar
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitel _titel;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhalt _inhalt;
        private string _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossar()
        {
            _inhalt = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhalt();
            _titel = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitel();
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhalt Inhalt
        {
            get
            {
                return _inhalt;
            }
            set
            {
                _inhalt = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitel
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitelLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitel()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitelLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitelLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarTitelLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhalt
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhaltLocalisationCH_V1MultilingualMText _localisationCH_V1MultilingualMText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhalt()
        {
            _localisationCH_V1MultilingualMText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhaltLocalisationCH_V1MultilingualMText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualMText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhaltLocalisationCH_V1MultilingualMText LocalisationCH_V1MultilingualMText
        {
            get
            {
                return _localisationCH_V1MultilingualMText;
            }
            set
            {
                _localisationCH_V1MultilingualMText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationGlossarInhaltLocalisationCH_V1MultilingualMText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedMText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedMText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedMText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedMText
    {
        #region Private fields
        private string _language;
        private string _text;
        #endregion

        public string Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }

        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweis
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitel _titel;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhalt _inhalt;
        private byte _auszugIndex;
        private string _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweis()
        {
            _inhalt = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhalt();
            _titel = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitel();
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhalt Inhalt
        {
            get
            {
                return _inhalt;
            }
            set
            {
                _inhalt = value;
            }
        }

        public byte AuszugIndex
        {
            get
            {
                return _auszugIndex;
            }
            set
            {
                _auszugIndex = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitel
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitelLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitel()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitelLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitelLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisTitelLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhalt
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhaltLocalisationCH_V1MultilingualMText _localisationCH_V1MultilingualMText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhalt()
        {
            _localisationCH_V1MultilingualMText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhaltLocalisationCH_V1MultilingualMText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualMText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhaltLocalisationCH_V1MultilingualMText LocalisationCH_V1MultilingualMText
        {
            get
            {
                return _localisationCH_V1MultilingualMText;
            }
            set
            {
                _localisationCH_V1MultilingualMText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationHaftungshinweisInhaltLocalisationCH_V1MultilingualMText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedMText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedMText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedMText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformation
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitel _titel;
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhalt _inhalt;
        private byte _auszugIndex;
        private string _tID;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformation()
        {
            _inhalt = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhalt();
            _titel = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitel();
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitel Titel
        {
            get
            {
                return _titel;
            }
            set
            {
                _titel = value;
            }
        }

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhalt Inhalt
        {
            get
            {
                return _inhalt;
            }
            set
            {
                _inhalt = value;
            }
        }

        public byte AuszugIndex
        {
            get
            {
                return _auszugIndex;
            }
            set
            {
                _auszugIndex = value;
            }
        }

        [XmlAttribute]
        public string TID
        {
            get
            {
                return _tID;
            }
            set
            {
                _tID = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitel
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitelLocalisationCH_V1MultilingualText _localisationCH_V1MultilingualText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitel()
        {
            _localisationCH_V1MultilingualText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitelLocalisationCH_V1MultilingualText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitelLocalisationCH_V1MultilingualText LocalisationCH_V1MultilingualText
        {
            get
            {
                return _localisationCH_V1MultilingualText;
            }
            set
            {
                _localisationCH_V1MultilingualText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationTitelLocalisationCH_V1MultilingualText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhalt
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhaltLocalisationCH_V1MultilingualMText _localisationCH_V1MultilingualMText;
        #endregion

        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhalt()
        {
            _localisationCH_V1MultilingualMText = new TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhaltLocalisationCH_V1MultilingualMText();
        }

        [XmlElement("LocalisationCH_V1.MultilingualMText")]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhaltLocalisationCH_V1MultilingualMText LocalisationCH_V1MultilingualMText
        {
            get
            {
                return _localisationCH_V1MultilingualMText;
            }
            set
            {
                _localisationCH_V1MultilingualMText = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.interlis.ch/INTERLIS2.3")]
    public partial class TRANSFERDATASECTIONOeREBKRMkvs_V2_0KonfigurationOeREBKRMkvs_V2_0KonfigurationInformationInhaltLocalisationCH_V1MultilingualMText
    {
        #region Private fields
        private TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedMText[] _localisedText;
        #endregion

        [XmlArrayItemAttribute("LocalisationCH_V1.LocalisedMText", IsNullable = false)]
        public TRANSFERDATASECTIONOeREBKRMkvs_V2_0LocalisedMText[] LocalisedText
        {
            get
            {
                return _localisedText;
            }
            set
            {
                _localisedText = value;
            }
        }
    }
}
#pragma warning restore
