//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/1.0/Versioning")]
[System.Xml.Serialization.XmlRootAttribute("GetVersionsResponse", Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/1.0/Versioning", IsNullable = false)]
public partial class GetVersionsResponseType
{

    private VersionType[] supportedVersionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("supportedVersion")]
    public VersionType[] supportedVersion
    {
        get
        {
            return this.supportedVersionField;
        }
        set
        {
            this.supportedVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/1.0/Versioning")]
public partial class VersionType
{

    private string versionField;

    private string serviceEndpointBaseField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
    public string serviceEndpointBase
    {
        get
        {
            return this.serviceEndpointBaseField;
        }
        set
        {
            this.serviceEndpointBaseField = value;
        }
    }
}
