/* $Rev: 29789 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net45","NameSpace":"ExtractDataModel_v20","CollectionObjectType":"Array","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ExtractDataModel_v20
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/1.0/Versioning")]
    [XmlRootAttribute("GetVersionsResponse", Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/1.0/Versioning", IsNullable = false)]
    public partial class GetVersionsResponseType
    {
        #region Private fields
        private VersionType[] _supportedVersion;
        #endregion

        [XmlElement("supportedVersion")]
        public VersionType[] supportedVersion
        {
            get
            {
                return _supportedVersion;
            }
            set
            {
                _supportedVersion = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schemas.geo.admin.ch/V_D/OeREB/1.0/Versioning")]
    public partial class VersionType
    {
        #region Private fields
        private string _version;
        private string _serviceEndpointBase;
        #endregion

        [XmlElement(DataType = "normalizedString")]
        public string version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }

        [XmlElement(DataType = "anyURI")]
        public string serviceEndpointBase
        {
            get
            {
                return _serviceEndpointBase;
            }
            set
            {
                _serviceEndpointBase = value;
            }
        }
    }
}
#pragma warning restore
