/* $Rev: 29789 $ */
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"Net45","NameSpace":"ExtractDataModel_v20","CollectionObjectType":"Array","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ExtractDataModel_v20
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("Signature", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class SignatureType
    {
        #region Private fields
        private SignedInfoType _signedInfo;
        private SignatureValueType _signatureValue;
        private KeyInfoType _keyInfo;
        private ObjectType[] _object;
        private string _id;
        #endregion

        public SignatureType()
        {
            _keyInfo = new KeyInfoType();
            _signatureValue = new SignatureValueType();
            _signedInfo = new SignedInfoType();
        }

        public SignedInfoType SignedInfo
        {
            get
            {
                return _signedInfo;
            }
            set
            {
                _signedInfo = value;
            }
        }

        public SignatureValueType SignatureValue
        {
            get
            {
                return _signatureValue;
            }
            set
            {
                _signatureValue = value;
            }
        }

        public KeyInfoType KeyInfo
        {
            get
            {
                return _keyInfo;
            }
            set
            {
                _keyInfo = value;
            }
        }

        [XmlElement("Object")]
        public ObjectType[] Object
        {
            get
            {
                return _object;
            }
            set
            {
                _object = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("SignedInfo", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class SignedInfoType
    {
        #region Private fields
        private CanonicalizationMethodType _canonicalizationMethod;
        private SignatureMethodType _signatureMethod;
        private ReferenceType[] _reference;
        private string _id;
        #endregion

        public SignedInfoType()
        {
            _signatureMethod = new SignatureMethodType();
            _canonicalizationMethod = new CanonicalizationMethodType();
        }

        public CanonicalizationMethodType CanonicalizationMethod
        {
            get
            {
                return _canonicalizationMethod;
            }
            set
            {
                _canonicalizationMethod = value;
            }
        }

        public SignatureMethodType SignatureMethod
        {
            get
            {
                return _signatureMethod;
            }
            set
            {
                _signatureMethod = value;
            }
        }

        [XmlElement("Reference")]
        public ReferenceType[] Reference
        {
            get
            {
                return _reference;
            }
            set
            {
                _reference = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("CanonicalizationMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class CanonicalizationMethodType
    {
        #region Private fields
        private System.Xml.XmlNode[] _any;
        private string _algorithm;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlAttribute]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Algorithm
        {
            get
            {
                return _algorithm;
            }
            set
            {
                _algorithm = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("Object", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class ObjectType
    {
        #region Private fields
        private System.Xml.XmlNode[] _any;
        private string _id;
        private string _mimeType;
        private string _encoding;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlAttribute]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        [XmlAttribute]
        public string MimeType
        {
            get
            {
                return _mimeType;
            }
            set
            {
                _mimeType = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Encoding
        {
            get
            {
                return _encoding;
            }
            set
            {
                _encoding = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("SPKIData", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class SPKIDataType
    {
        #region Private fields
        private byte[][] _sPKISexp;
        private System.Xml.XmlElement _any;
        #endregion

        [XmlElement("SPKISexp", DataType = "base64Binary")]
        public byte[][] SPKISexp
        {
            get
            {
                return _sPKISexp;
            }
            set
            {
                _sPKISexp = value;
            }
        }

        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("PGPData", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class PGPDataType
    {
        #region Private fields
        private object[] _items;
        private ItemsChoiceType1[] _itemsElementName;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlElement("PGPKeyID", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("PGPKeyPacket", typeof(byte[]), DataType = "base64Binary")]
        [XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        [XmlElement("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return _itemsElementName;
            }
            set
            {
                _itemsElementName = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {
        [XmlEnumAttribute("##any:")]
        Item,
        PGPKeyID,
        PGPKeyPacket,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType
    {
        #region Private fields
        private string _x509IssuerName;
        private string _x509SerialNumber;
        #endregion

        public string X509IssuerName
        {
            get
            {
                return _x509IssuerName;
            }
            set
            {
                _x509IssuerName = value;
            }
        }

        [XmlElement(DataType = "integer")]
        public string X509SerialNumber
        {
            get
            {
                return _x509SerialNumber;
            }
            set
            {
                _x509SerialNumber = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("X509Data", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class X509DataType
    {
        #region Private fields
        private object[] _items;
        private ItemsChoiceType[] _itemsElementName;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlElement("X509CRL", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("X509Certificate", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("X509IssuerSerial", typeof(X509IssuerSerialType))]
        [XmlElement("X509SKI", typeof(byte[]), DataType = "base64Binary")]
        [XmlElement("X509SubjectName", typeof(string))]
        [XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        [XmlElement("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return _itemsElementName;
            }
            set
            {
                _itemsElementName = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        [XmlEnumAttribute("##any:")]
        Item,
        X509CRL,
        X509Certificate,
        X509IssuerSerial,
        X509SKI,
        X509SubjectName,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("RetrievalMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class RetrievalMethodType
    {
        #region Private fields
        private TransformType[] _transforms;
        private string _uRI;
        private string _type;
        #endregion

        [XmlArrayItemAttribute("Transform", IsNullable = false)]
        public TransformType[] Transforms
        {
            get
            {
                return _transforms;
            }
            set
            {
                _transforms = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string URI
        {
            get
            {
                return _uRI;
            }
            set
            {
                _uRI = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("Transform", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class TransformType
    {
        #region Private fields
        private object[] _items;
        private string[] _text;
        private string _algorithm;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlElement("XPath", typeof(string))]
        public object[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        [XmlAttribute]
        public string[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Algorithm
        {
            get
            {
                return _algorithm;
            }
            set
            {
                _algorithm = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("RSAKeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class RSAKeyValueType
    {
        #region Private fields
        private byte[] _modulus;
        private byte[] _exponent;
        #endregion

        [XmlElement(DataType = "base64Binary")]
        public byte[] Modulus
        {
            get
            {
                return _modulus;
            }
            set
            {
                _modulus = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] Exponent
        {
            get
            {
                return _exponent;
            }
            set
            {
                _exponent = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("DSAKeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class DSAKeyValueType
    {
        #region Private fields
        private byte[] _p;
        private byte[] _q;
        private byte[] _g;
        private byte[] _y;
        private byte[] _j;
        private byte[] _seed;
        private byte[] _pgenCounter;
        #endregion

        [XmlElement(DataType = "base64Binary")]
        public byte[] P
        {
            get
            {
                return _p;
            }
            set
            {
                _p = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] Q
        {
            get
            {
                return _q;
            }
            set
            {
                _q = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] G
        {
            get
            {
                return _g;
            }
            set
            {
                _g = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] J
        {
            get
            {
                return _j;
            }
            set
            {
                _j = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] Seed
        {
            get
            {
                return _seed;
            }
            set
            {
                _seed = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] PgenCounter
        {
            get
            {
                return _pgenCounter;
            }
            set
            {
                _pgenCounter = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("KeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class KeyValueType
    {
        #region Private fields
        private object _item;
        private string[] _text;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlElement("DSAKeyValue", typeof(DSAKeyValueType))]
        [XmlElement("RSAKeyValue", typeof(RSAKeyValueType))]
        public object Item
        {
            get
            {
                return _item;
            }
            set
            {
                _item = value;
            }
        }

        [XmlAttribute]
        public string[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("KeyInfo", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class KeyInfoType
    {
        #region Private fields
        private object[] _items;
        private ItemsChoiceType2[] _itemsElementName;
        private string[] _text;
        private string _id;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlElement("KeyName", typeof(string))]
        [XmlElement("KeyValue", typeof(KeyValueType))]
        [XmlElement("MgmtData", typeof(string))]
        [XmlElement("PGPData", typeof(PGPDataType))]
        [XmlElement("RetrievalMethod", typeof(RetrievalMethodType))]
        [XmlElement("SPKIData", typeof(SPKIDataType))]
        [XmlElement("X509Data", typeof(X509DataType))]
        [XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        [XmlElement("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType2[] ItemsElementName
        {
            get
            {
                return _itemsElementName;
            }
            set
            {
                _itemsElementName = value;
            }
        }

        [XmlAttribute]
        public string[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
    public enum ItemsChoiceType2
    {
        [XmlEnumAttribute("##any:")]
        Item,
        KeyName,
        KeyValue,
        MgmtData,
        PGPData,
        RetrievalMethod,
        SPKIData,
        X509Data,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("SignatureValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class SignatureValueType
    {
        #region Private fields
        private string _id;
        private byte[] _value;
        #endregion

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        [XmlAttribute]
        public byte[] Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("DigestMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class DigestMethodType
    {
        #region Private fields
        private System.Xml.XmlNode[] _any;
        private string _algorithm;
        #endregion

        [XmlAnyElementAttribute()]
        [XmlAttribute]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Algorithm
        {
            get
            {
                return _algorithm;
            }
            set
            {
                _algorithm = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("Reference", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class ReferenceType
    {
        #region Private fields
        private TransformType[] _transforms;
        private DigestMethodType _digestMethod;
        private byte[] _digestValue;
        private string _id;
        private string _uRI;
        private string _type;
        #endregion

        public ReferenceType()
        {
            _digestMethod = new DigestMethodType();
        }

        [XmlArrayItemAttribute("Transform", IsNullable = false)]
        public TransformType[] Transforms
        {
            get
            {
                return _transforms;
            }
            set
            {
                _transforms = value;
            }
        }

        public DigestMethodType DigestMethod
        {
            get
            {
                return _digestMethod;
            }
            set
            {
                _digestMethod = value;
            }
        }

        [XmlElement(DataType = "base64Binary")]
        public byte[] DigestValue
        {
            get
            {
                return _digestValue;
            }
            set
            {
                _digestValue = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string URI
        {
            get
            {
                return _uRI;
            }
            set
            {
                _uRI = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("SignatureMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class SignatureMethodType
    {
        #region Private fields
        private string _hMACOutputLength;
        private System.Xml.XmlNode[] _any;
        private string _algorithm;
        #endregion

        [XmlElement(DataType = "integer")]
        public string HMACOutputLength
        {
            get
            {
                return _hMACOutputLength;
            }
            set
            {
                _hMACOutputLength = value;
            }
        }

        [XmlAnyElementAttribute()]
        [XmlAttribute]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Algorithm
        {
            get
            {
                return _algorithm;
            }
            set
            {
                _algorithm = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("Transforms", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class TransformsType
    {
        #region Private fields
        private TransformType[] _transform;
        #endregion

        [XmlElement("Transform")]
        public TransformType[] Transform
        {
            get
            {
                return _transform;
            }
            set
            {
                _transform = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("Manifest", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class ManifestType
    {
        #region Private fields
        private ReferenceType[] _reference;
        private string _id;
        #endregion

        [XmlElement("Reference")]
        public ReferenceType[] Reference
        {
            get
            {
                return _reference;
            }
            set
            {
                _reference = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("SignatureProperties", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class SignaturePropertiesType
    {
        #region Private fields
        private SignaturePropertyType[] _signatureProperty;
        private string _id;
        #endregion

        [XmlElement("SignatureProperty")]
        public SignaturePropertyType[] SignatureProperty
        {
            get
            {
                return _signatureProperty;
            }
            set
            {
                _signatureProperty = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [XmlRootAttribute("SignatureProperty", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public partial class SignaturePropertyType
    {
        #region Private fields
        private System.Xml.XmlElement[] _items;
        private string[] _text;
        private string _target;
        private string _id;
        #endregion

        [XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        [XmlAttribute]
        public string[] Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
            }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string Target
        {
            get
            {
                return _target;
            }
            set
            {
                _target = value;
            }
        }

        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }
}
#pragma warning restore
