---
app: "9888"
src: "src"
os_type: 'windows'
product: 'iis'
artifact_repository_name: 'thirdparty'
artifact_group_id: 'ch.ge.ter'
artifact_id: "{{ app }}"
artifact_ext: 'zip'
artifact_classifier: ""
artifact_file_name: "{{ artifact_id }}-{{ version }}.{{ artifact_ext }}"
deploy_releases_folder_suffix: ''
deploy_releases_folder: "D:\\exploitation\\{{ app }}{{ deploy_releases_folder_suffix }}"
deploy_releases_folders_mode: '0755'
deploy_releases_files_mode: '0644'

win_iis_webapppool_name: '9888_terecadastrews'
win_iis_webapplication_name: 'terecadastrews'
win_iis_webapplication_site: 'DEV'
win_iis_webapppool_attributes: 'managedRuntimeVersion:v4.0|enable32BitAppOnWin64:false'

stages:
  dev:
    hosts: "geoweb03"
    ReverseProxyAGS: "https://dev.etat-ge.ch/terags"
    WebsiteUrl: "https://dev.etat-ge.ch/terecadastrews"
    UseTrace: "false"
  rec:
    hosts: "geoappweb02"
    ReverseProxyAGS: "https://rec.etat-ge.ch/terags"
    WebsiteUrl: "https://rec.etat-ge.ch/terecadastrews"
    UseTrace: "true"
  prod:
    hosts: "geoappweb01"
    ReverseProxyAGS: "https://prod.etat-ge.ch/terags"
    WebsiteUrl: "https://prod.etat-ge.ch/terecadastrews"
    UseTrace: "true"

# secure_env_variables:
#   - db_password

app_templates:
  - web.config